import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { INDUSTRIES } from '@/data/industries';
import { SOLUTIONS } from '@/data/solutions';
import { CASE_STUDIES } from '@/data/caseStudies';
import { ALL_SERVICES } from '@/data/services';
import SectionHeading from './SectionHeading';
import ServicePillars from './ServicePillars';

export default function HomeExperience() {
  return <>
    <section className="hero-modern"><div className="container-shell grid items-center gap-16 lg:grid-cols-[1.05fr_.95fr]"><div><p className="eyebrow text-blue-700">AI / SOFTWARE / QUALITY / CLOUD</p><h1 className="hero-title">Technology that turns <em>complexity</em> into opportunity.</h1><p className="hero-copy">LogicLayer Solutions helps businesses transform difficult technology challenges into scalable, secure, and intelligent digital systems.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/schedule" className="btn-primary">Schedule With Us <ArrowUpRight size={16} /></Link><Link href="/services" className="btn-outline">Explore Our Services <ArrowUpRight size={16} /></Link></div><div className="mt-12 grid max-w-xl grid-cols-3 gap-5 border-t border-slate-300 pt-5"><div><strong className="metric">BUILD</strong><span className="metric-label">New products</span></div><div><strong className="metric">ASSURE</strong><span className="metric-label">Better quality</span></div><div><strong className="metric">TRANSFORM</strong><span className="metric-label">Smarter operations</span></div></div></div><div className="capability-visual"><div className="capability-header"><span>LOGIC / LAYER</span><span>09 CAPABILITIES</span></div><div className="capability-network"><div className="capability-lines" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><div className="capability-core"><span>LL</span><strong>Technology<br />that moves</strong></div><div className="capability-hub hub-build"><span>01</span><strong>BUILD</strong><small>Products</small></div><div className="capability-hub hub-assure"><span>02</span><strong>ASSURE</strong><small>Quality</small></div><div className="capability-hub hub-transform"><span>03</span><strong>TRANSFORM</strong><small>Scale</small></div>{ALL_SERVICES.map((service, index) => <Link key={service.id} href={`/services/${service.slug}`} className={`capability-node node-${index + 1}`}><span>{String(index + 1).padStart(2, '0')}</span>{service.title}</Link>)}</div><div className="capability-footer">Three practices / nine ways to move forward <ArrowUpRight size={15} /></div></div></div></section>
    <ServicePillars />
    <section className="section-pad bg-slate-950 text-white"><div className="container-shell grid gap-14 lg:grid-cols-[.85fr_1.15fr]"><SectionHeading dark eyebrow="02 / BUSINESS OUTCOMES" title={<>What are you <em>trying to change?</em></>} description="The best technology plan starts with a business question, not a shopping list of tools." /><div className="grid gap-3 sm:grid-cols-2">{SOLUTIONS.slice(0, 4).map((solution, index) => <Link href="/schedule" key={solution.id} className="outcome-card"><span>0{index + 1}</span><h3>{solution.title}</h3><p>{solution.description}</p><ArrowUpRight size={18} /></Link>)}</div></div></section>
    <section className="section-pad bg-[#f6f6f1]"><div className="container-shell"><SectionHeading eyebrow="03 / WHERE WE HELP" title={<>Built for <em className="text-orange-500">high-stakes</em> work.</>} description="Different industries bring different constraints. Our delivery model stays thoughtful, practical, and adaptable." /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{INDUSTRIES.map((industry, index) => <Link href="/industries" key={industry.id} className="industry-card"><span>0{index + 1}</span><h3>{industry.name}</h3><p>{industry.description}</p><small>{industry.focus}</small></Link>)}</div></div></section>
    <section className="section-pad bg-yellow-300"><div className="container-shell grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="04 / HOW WE WORK" title={<>Clear thinking. <em className="text-blue-700">Useful momentum.</em></>} description="A transparent process for moving from uncertainty to a system your team can own." /><div className="process-list">{['Frame the real constraint', 'Shape a practical path', 'Build in visible increments', 'Strengthen what comes next'].map((step, index) => <div key={step} className="process-item"><span>0{index + 1}</span><div><h3>{step}</h3><p>{['Clarify the outcome, context, and decisions that matter.', 'Turn ambiguity into architecture, priorities, and shared language.', 'Ship, learn, and keep the work connected to the goal.', 'Leave behind quality, capability, and momentum.'][index]}</p></div></div>)}</div></div></section>
    <section className="section-pad bg-white"><div className="container-shell"><SectionHeading eyebrow="05 / SELECTED PERSPECTIVES" title={<>Proof over <em className="text-orange-500">promises.</em></>} description="A few examples of the questions we help teams answer." /><div className="grid gap-5 lg:grid-cols-3">{CASE_STUDIES.map((study) => <article key={study.id} className="case-card"><span>{study.industry}</span><h3>{study.title}</h3><p>{study.result}</p><div>{study.services.map((service) => <small key={service}>{service}</small>)}</div></article>)}</div></div></section>
    <section className="cta-band"><div className="container-shell grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><p className="eyebrow text-yellow-300">READY TO BUILD WHAT'S NEXT?</p><h2>Bring the hard <em>part.</em></h2><p>Whether you are building, modernizing, automating, or improving quality, let&apos;s start with a useful conversation.</p></div><Link href="/schedule" className="btn-yellow">Schedule With Us <ArrowUpRight size={16} /></Link></div></section>
  </>;
}
